/**
 * ============================================================================
 *  THE RIVERFRONT RESORT & CAMPING — CENTRAL SITE DATA
 * ============================================================================
 *  This is the ONLY file you normally need to edit to update the website.
 *
 *  HOW TO CHANGE TEXT / PHONE / LINKS:  Edit the values below. The rest of the
 *  website reads everything from here automatically.
 *
 *  HOW TO CHANGE IMAGES:
 *  - Drop any .jpg/.jpeg/.png into a folder inside assets/images/
 *    (no naming conventions needed), run  python scripts/generate-images.py
 *    and refresh the page. Images are picked up automatically.
 *  - If a matching .webp file (same name) exists, browsers show that faster
 *    version; otherwise the original image is shown.
 *  - All current images are PLACEHOLDER illustrations, not photos of the
 *    actual resort.
 * ============================================================================
 */

(function () {
  "use strict";

  /** Build a photo object from an image path + alt text.
   *  The .webp path is derived automatically for jpg/jpeg/png/gif. */
  function photo(jpgPath, alt, category) {
    return {
      jpg: jpgPath,
      webp: jpgPath.replace(/\.(jpg|jpeg|png|gif)$/i, ".webp"),
      alt: alt,
      category: category || "",
    };
  }

  /* ------------------------------------------------------------------ */
  /*  AUTOMATIC IMAGE LOADING (generated by scripts/generate-images.py)  */
  /*  Drop any .jpg/.jpeg/.png into a folder inside assets/images/, run  */
  /*  `python scripts/generate-images.py`, refresh — the site picks the  */
  /*  images up automatically. No naming conventions needed.             */
  /* ------------------------------------------------------------------ */
  var IMG = window.IMAGE_MANIFEST || null;

  // Return the image at `index` (or the first) in a category folder.
  function pick(category, index) {
    var list = (IMG && IMG[category]) || [];
    var item = list[index] || list[0];
    if (!item) return null;
    return {
      jpg: item.jpg,
      webp: item.webp || "",
      alt: item.alt || "",
      category: item.category || category,
    };
  }

  // Combine every category folder into the gallery, in display order.
  function galleryFromFolders() {
    var out = [];
    if (!IMG) return out;
    var order = [
      "gallery",
      "resort",
      "rooms",
      "camping",
      "pool",
      "food",
      "activities",
      "surroundings",
    ];
    order.forEach(function (cat) {
      (IMG[cat] || []).forEach(function (p) {
        out.push({
          jpg: p.jpg,
          webp: p.webp || "",
          alt: p.alt || "",
          category: p.category || cat,
        });
      });
    });
    return out;
  }

  var RESORT_DATA = {
    /* ------------------------------------------------------------------ */
    /*  BRANDING & CONTACT                                                  */
    /* ------------------------------------------------------------------ */
    name: "The Riverfront Resort & Camping",
    shortName: "The Riverfront",
    tagline: "Relax by nature. Stay in comfort. Create unforgettable memories.",

    /* ------------------------------------------------------------------ */
    /*  SEO — shown in browser tabs, Google results & social shares.        */
    /* ------------------------------------------------------------------ */
    seo: {
      title: "The Riverfront Resort & Camping | Relax by nature",
      description:
        "The Riverfront Resort & Camping — a peaceful riverside resort in Pimpri-Chinchwad for families, couples, groups and pet owners. Rooms, camping, amenities and a welcoming atmosphere.",
    },
    // logo / favicon live in assets/images/branding/
    logo: {
      image: "assets/images/branding/resort-logo.png",
      alt: "The Riverfront Resort & Camping logo",
    },
    favicon: "assets/images/branding/resort-favicon.png",

    phone: {
      display: "072777 75060",
      tel: "+917277775060",
    },

    whatsapp: {
      // ==========================================================
      //  ⭐ SINGLE WHATSAPP NUMBER USED EVERYWHERE:
      //  - "Book Now" / "Book Your Stay" buttons
      //  - "Enquire Now" on every Stay card
      //  - Location + Footer WhatsApp buttons
      //  - The enquiry form (opens WhatsApp with the form details)
      //  Format: country code + number, digits only (no +, no spaces).
      //  e.g. 917277775060 for +91 72777 75060
      // ==========================================================
      number: "917277775060",
      // default message used by the "Book Your Stay" / "Book Now" buttons
      message:
        "Hello, I would like to enquire about availability at The Riverfront Resort & Camping.",
    },

    /* ------------------------------------------------------------------ */
    /*  NAVIGATION                                                          */
    /* ------------------------------------------------------------------ */
    nav: [
      { label: "Home", href: "#home" },
      { label: "About", href: "#about" },
      { label: "Stay & Camping", href: "#stay" },
      { label: "Amenities", href: "#amenities" },
      { label: "Gallery", href: "#gallery" },
      { label: "Location", href: "#location" },
      { label: "Contact", href: "#contact" },
    ],

    /* ------------------------------------------------------------------ */
    /*  UI TEXTS — every visible heading, label and button on the page.    */
    /*  Change these to rebrand the whole site for any client.             */
    /* ------------------------------------------------------------------ */
    ui: {
      nameSub: "Resort & Camping", // small tagline under the brand name
      navBook: "Book Now",
      hero: { book: "Book Your Stay", call: "Call Now" },
      about: {
        eyebrow: "About the Resort",
        title: "A peaceful escape on the riverfront",
        explore: "Explore Stays",
        wa: "Enquire on WhatsApp",
      },
      stay: {
        eyebrow: "Stay & Camping",
        title: "Choose your stay",
        sub: "Comfortable rooms and a true camping experience by the river — perfect for families, couples, groups and pets.",
        enquire: "Enquire Now",
      },
      amenities: {
        eyebrow: "Amenities",
        title: "Everything you need for a comfortable stay",
        sub: "From the swimming pool to pet-friendly facilities — enjoy a relaxed, easy getaway.",
      },
      gallery: {
        eyebrow: "Gallery",
        title: "Moments at The Riverfront",
        sub: "A glimpse of the resort, rooms, camping, pool, food and surroundings.",
      },
      info: {
        eyebrow: "Good to Know",
        title: "Important information",
        checkIn: "Check-in",
        checkOut: "Check-out",
      },
      location: {
        eyebrow: "Location",
        title: "Find Us",
        directions: "Get Directions",
        call: "Call Resort",
        wa: "WhatsApp",
      },
      contact: {
        eyebrow: "Contact",
        title: "Send us an enquiry",
        intro: "Tell us about your stay and we will get back to you on WhatsApp with availability.",
        formTitle: "Enquiry Form",
        labels: {
          name: "Full name",
          phone: "Phone number",
          checkin: "Check-in date",
          checkout: "Check-out date",
          adults: "Number of adults",
          children: "Number of children",
          preference: "Stay preference",
          message: "Message",
        },
        placeholders: {
          name: "Your full name",
          phone: "e.g. 98200 00000",
          message: "Tell us about your planned stay…",
        },
        required: ["name", "phone"], // field keys that show a red *
        submit: "Send Enquiry",
        hint: "Your enquiry opens in WhatsApp — no account or backend needed.",
        preferences: ["Room", "Camping", "Group Outing"],
      },
      footer: {
        quickLinks: "Quick Links",
        contact: "Contact",
        wa: "WhatsApp Us",
      },
    },

    /* ------------------------------------------------------------------ */
    /*  HERO (section: hero)                                                */
    /*  hero-main.jpg  = desktop hero       hero-mobile.jpg = mobile hero   */
    /* ------------------------------------------------------------------ */
    hero: {
      heading: "The Riverfront Resort & Camping",
      subtitle:
        "Relax by nature. Stay in comfort. Create unforgettable memories.",
      images: (function () {
        var desktop =
          pick("hero", 0) ||
          photo(
            "assets/images/hero/hero-main.jpg",
            "Riverside view of The Riverfront Resort & Camping at dusk"
          );
        var mobile =
          pick("hero", 1) ||
          photo(
            "assets/images/hero/hero-mobile.jpg",
            "Peaceful riverside view at The Riverfront Resort & Camping"
          );
        return [desktop, mobile];
      })(),
    },

    /* ------------------------------------------------------------------ */
    /*  ABOUT (section: about)                                              */
    /* ------------------------------------------------------------------ */
    about: {
      text: "Escape the noise of the city and enjoy a peaceful stay surrounded by nature at The Riverfront Resort & Camping. Whether you are planning a relaxing family holiday, a group outing, a camping experience, or a weekend getaway, the resort offers comfortable facilities, delicious food, and a welcoming atmosphere.",
      image:
        pick("resort", 0) ||
        photo(
          "assets/images/resort/resort-riverfront-01.jpg",
          "The riverfront edge of the resort surrounded by green trees"
        ),
      imageB:
        pick("resort", 1) ||
        photo(
          "assets/images/resort/resort-exterior-01.jpg",
          "Exterior view of the resort buildings among gardens"
        ),
    },

    /* ------------------------------------------------------------------ */
    /*  STAY & CAMPING CARDS (section: stay)                                */
    /* ------------------------------------------------------------------ */
    stays: [
      {
        id: "resort-rooms",
        title: "Resort Rooms",
        description:
          "Comfortable, well-furnished rooms designed for a relaxed riverside stay.",
        image:
          pick("rooms", 0) ||
          photo(
            "assets/images/rooms/room-01.jpg",
            "A bright and comfortable resort room"
          ),
        facilities: [
          "Air conditioning",
          "Private bathroom",
          "Shower",
          "Kitchen facilities",
        ],
      },
      {
        id: "camping",
        title: "Camping Experience",
        description:
          "Spend the night under the open sky, close to the river and the sound of nature.",
        image:
          pick("camping", 0) ||
          photo(
            "assets/images/camping/camping-01.jpg",
            "Camping tents set up in the resort grounds"
          ),
        facilities: [
          "Open-air stay",
          "Bonfire",
          "Nature setting",
          "Group friendly",
        ],
      },
      {
        id: "family",
        title: "Family Stay",
        description:
          "A safe, friendly and spacious stay made for families travelling with children.",
        image:
          pick("rooms", 1) ||
          pick("rooms", 0) ||
          photo(
            "assets/images/rooms/room-02.jpg",
            "Spacious family room at the resort"
          ),
        facilities: [
          "Child friendly",
          "Spacious rooms",
          "Comfortable beds",
          "Kitchen facilities",
        ],
      },
      {
        id: "group",
        title: "Group Outings",
        description:
          "The perfect riverside venue for group trips, outings and memorable getaways together.",
        image:
          pick("activities", 0) ||
          photo(
            "assets/images/activities/activity-group-01.jpg",
            "A group of guests enjoying time together at the resort"
          ),
        facilities: [
          "Group friendly",
          "Ample space",
          "Food and drink",
          "Activities",
        ],
      },
    ],
    // shared note shown below the stay cards
    stayNote:
      "Resort room facilities include air conditioning, private bathroom, shower and kitchen facilities. For rates and availability, use the Enquire Now buttons below.",

    /* ------------------------------------------------------------------ */
    /*  AMENITIES (section: amenities) — each item needs an icon            */
    /*  Add new icons in js/main.js inside the ICONS object.                */
    /* ------------------------------------------------------------------ */
    amenities: {
      popular: {
        title: "Popular Amenities",
        items: [
          { icon: "pool", label: "Swimming pool" },
          { icon: "parking", label: "Free parking" },
          { icon: "ac", label: "Air conditioning" },
          { icon: "coffee", label: "Breakfast" },
          { icon: "wifi", label: "Wi-Fi" },
          { icon: "food", label: "Food and drink" },
          { icon: "service", label: "Table service" },
          { icon: "buffet", label: "Buffet dinner" },
          { icon: "roomsvc", label: "Room service" },
          { icon: "breakfast", label: "Breakfast buffet" },
        ],
      },
      services: {
        title: "Services",
        items: [
          { icon: "storage", label: "Baggage storage" },
          { icon: "cleaning", label: "Daily housekeeping" },
          { icon: "shuttle", label: "Local shuttle service" },
        ],
      },
      family: {
        title: "Family & Accessibility",
        items: [
          { icon: "child", label: "Child-friendly property" },
          { icon: "accessible", label: "Accessible premises" },
          { icon: "parking", label: "Accessible parking" },
          { icon: "pet", label: "Pet-friendly facilities" },
          { icon: "petfree", label: "Pets stay free" },
          { icon: "dog", label: "Dogs allowed" },
          { icon: "cat", label: "Cats allowed" },
        ],
      },
      languages: {
        title: "Languages Spoken",
        items: [
          { icon: "en", label: "English" },
          { icon: "hi", label: "Hindi" },
        ],
      },
    },

    /* ------------------------------------------------------------------ */
    /*  GALLERY (section: gallery) — filters map to `category` values       */
    /* ------------------------------------------------------------------ */
    galleryFilters: [
      "All",
      "Resort",
      "Rooms",
      "Camping",
      "Swimming Pool",
      "Food",
      "Activities",
      "Surroundings",
    ],
    gallery: (function () {
      var auto = galleryFromFolders();
      if (auto.length) return auto;
      return [
        photo("assets/images/gallery/gallery-01.jpg", "Riverside view at the resort", "Resort"),
        photo("assets/images/resort/resort-exterior-01.jpg", "Resort exterior surrounded by gardens", "Resort"),
        photo("assets/images/gallery/gallery-04.jpg", "Serene resort surroundings by the water", "Resort"),
        photo("assets/images/gallery/gallery-02.jpg", "Comfortable room interior at the resort", "Rooms"),
        photo("assets/images/rooms/room-03.jpg", "Another cosy room at the resort", "Rooms"),
        photo("assets/images/rooms/room-bathroom-01.jpg", "Private bathroom with shower", "Rooms"),
        photo("assets/images/gallery/gallery-03.jpg", "Camping setup in the resort grounds", "Camping"),
        photo("assets/images/camping/camping-night-01.jpg", "Camping under the night sky", "Camping"),
        photo("assets/images/camping/camping-02.jpg", "Camping tents by the greenery", "Camping"),
        photo("assets/images/pool/swimming-pool-01.jpg", "Swimming pool at the resort", "Swimming Pool"),
        photo("assets/images/pool/swimming-pool-02.jpg", "Relaxing at the swimming pool", "Swimming Pool"),
        photo("assets/images/food/food-breakfast-01.jpg", "Breakfast spread at the resort", "Food"),
        photo("assets/images/food/food-buffet-01.jpg", "Buffet dinner spread", "Food"),
        photo("assets/images/food/food-dinner-01.jpg", "Dinner served at the resort", "Food"),
        photo("assets/images/activities/activity-family-01.jpg", "Family enjoying activities together", "Activities"),
        photo("assets/images/activities/activity-group-01.jpg", "Group activities at the resort", "Activities"),
        photo("assets/images/surroundings/surroundings-01.jpg", "Beautiful surroundings near the river", "Surroundings"),
        photo("assets/images/surroundings/surroundings-02.jpg", "Nature around the resort", "Surroundings"),
      ];
    })(),

    /* ------------------------------------------------------------------ */
    /*  IMPORTANT INFORMATION (section: info)                               */
    /* ------------------------------------------------------------------ */
    importantInfo: {
      checkIn: "4:00 PM",
      checkOut: "10:00 AM",
      items: [
        "Smoke-free property",
        "Credit cards are not accepted",
        "Debit cards accepted",
        "NFC mobile payments accepted",
        "Cash accepted",
        "No hot tub",
        "No fitness centre",
      ],
    },

    /* ------------------------------------------------------------------ */
    /*  LOCATION (section: location)                                        */
    /* ------------------------------------------------------------------ */
    location: {
      addressLines: [
        "The Riverfront Resort & Camping",
        "Solu, Alandi-Markal Road, behind Dosti Hotel,",
        "Pimpri-Chinchwad, Maharashtra 412105",
      ],
// full address used in the map search & directions link
      fullAddress:
        "The Riverfront Resort & Camping, Solu, Alandi-Markal Road, behind Dosti Hotel, Pimpri-Chinchwad, Maharashtra 412105",
      // ==========================================================
      //  ⭐ GOOGLE MAP — paste any Google Maps embed URL here to
      //  point the map at a different address.
      //  To get one: open maps.google.com → search the address →
      //  Share → Embed a map → copy the "src=" URL.
      // ==========================================================
      mapEmbedSrc:
        "https://www.google.com/maps?q=" +
        encodeURIComponent(
          "The Riverfront Resort & Camping, Solu, Alandi-Markal Road, behind Dosti Hotel, Pimpri-Chinchwad, Maharashtra 412105"
        ) +
        "&output=embed",
      // "Get Directions" button — uses the same address
      directionsUrl:
        "https://www.google.com/maps/dir/?api=1&destination=" +
        encodeURIComponent(
          "The Riverfront Resort & Camping, Solu, Alandi-Markal Road, behind Dosti Hotel, Pimpri-Chinchwad, Maharashtra 412105"
        ),
      image:
        pick("surroundings", 0) ||
        photo(
          "assets/images/surroundings/surroundings-02.jpg",
          "Surroundings and nature around the resort location"
        ),
    },

    /* ------------------------------------------------------------------ */
    /*  FOOTER                                                              */
    /* ------------------------------------------------------------------ */
    footer: {
      note: "Escape the noise of the city and enjoy a peaceful riverside stay.",
      quickLinks: [
        { label: "Home", href: "#home" },
        { label: "About", href: "#about" },
        { label: "Stay & Camping", href: "#stay" },
        { label: "Amenities", href: "#amenities" },
        { label: "Gallery", href: "#gallery" },
        { label: "Location", href: "#location" },
        { label: "Contact", href: "#contact" },
      ],
      social: [
        { icon: "facebook", label: "Facebook", href: "#" },
        { icon: "instagram", label: "Instagram", href: "#" },
        { icon: "youtube", label: "YouTube", href: "#" },
      ],
      // shown in the copyright line
      copyrightHolder: "The Riverfront Resort & Camping",
    },
  };

  // expose globally
  window.RESORT_DATA = RESORT_DATA;
})();
