/* AUTO-GENERATED by scripts/generate-images.py — do not edit. */
window.IMAGE_MANIFEST = {
  "activities": [
    {
      "jpg": "assets/images/activities/activity-family-01.jpg",
      "webp": "assets/images/activities/activity-family-01.webp",
      "alt": "Activity Family 01",
      "category": "Activities"
    },
    {
      "jpg": "assets/images/activities/activity-group-01.jpg",
      "webp": "assets/images/activities/activity-group-01.webp",
      "alt": "Activity Group 01",
      "category": "Activities"
    },
    {
      "jpg": "assets/images/activities/activity-group-02.jpg",
      "webp": "",
      "alt": "Activity Group 02",
      "category": "Activities"
    },
    {
      "jpg": "assets/images/activities/activity-group-03.jpg",
      "webp": "",
      "alt": "Activity Group 03",
      "category": "Activities"
    },
    {
      "jpg": "assets/images/activities/activity-group-04.jpg",
      "webp": "",
      "alt": "Activity Group 04",
      "category": "Activities"
    },
    {
      "jpg": "assets/images/activities/activity-group-05.jpg",
      "webp": "",
      "alt": "Activity Group 05",
      "category": "Activities"
    },
    {
      "jpg": "assets/images/activities/activity-group-06.jpg",
      "webp": "",
      "alt": "Activity Group 06",
      "category": "Activities"
    },
    {
      "jpg": "assets/images/activities/activity-group-07.jpg",
      "webp": "",
      "alt": "Activity Group 07",
      "category": "Activities"
    }
  ],
  "branding": [
    {
      "jpg": "assets/images/branding/resort-favicon.png",
      "webp": "",
      "alt": "Resort Favicon",
      "category": ""
    },
    {
      "jpg": "assets/images/branding/resort-logo.png",
      "webp": "",
      "alt": "Resort Logo",
      "category": ""
    }
  ],
  "camping": [
    {
      "jpg": "assets/images/camping/camping-01.jpg",
      "webp": "assets/images/camping/camping-01.webp",
      "alt": "Camping 01",
      "category": "Camping"
    },
    {
      "jpg": "assets/images/camping/camping-02.jpg",
      "webp": "assets/images/camping/camping-02.webp",
      "alt": "Camping 02",
      "category": "Camping"
    },
    {
      "jpg": "assets/images/camping/camping-night-01.jpg",
      "webp": "assets/images/camping/camping-night-01.webp",
      "alt": "Camping Night 01",
      "category": "Camping"
    }
  ],
  "food": [
    {
      "jpg": "assets/images/food/food-breakfast-01.jpg",
      "webp": "assets/images/food/food-breakfast-01.webp",
      "alt": "Food Breakfast 01",
      "category": "Food"
    },
    {
      "jpg": "assets/images/food/food-buffet-01.jpg",
      "webp": "assets/images/food/food-buffet-01.webp",
      "alt": "Food Buffet 01",
      "category": "Food"
    },
    {
      "jpg": "assets/images/food/food-dinner-01.jpg",
      "webp": "assets/images/food/food-dinner-01.webp",
      "alt": "Food Dinner 01",
      "category": "Food"
    }
  ],
  "gallery": [
    {
      "jpg": "assets/images/gallery/gallery-01.jpg",
      "webp": "assets/images/gallery/gallery-01.webp",
      "alt": "Gallery 01",
      "category": "Resort"
    },
    {
      "jpg": "assets/images/gallery/gallery-02.jpg",
      "webp": "assets/images/gallery/gallery-02.webp",
      "alt": "Gallery 02",
      "category": "Resort"
    },
    {
      "jpg": "assets/images/gallery/gallery-03.jpg",
      "webp": "assets/images/gallery/gallery-03.webp",
      "alt": "Gallery 03",
      "category": "Resort"
    },
    {
      "jpg": "assets/images/gallery/gallery-04.jpg",
      "webp": "assets/images/gallery/gallery-04.webp",
      "alt": "Gallery 04",
      "category": "Resort"
    }
  ],
  "hero": [
    {
      "jpg": "assets/images/hero/hero-main.jpg",
      "webp": "assets/images/hero/hero-main.webp",
      "alt": "Hero Main",
      "category": "Hero"
    },
    {
      "jpg": "assets/images/hero/hero-mobile.jpg",
      "webp": "assets/images/hero/hero-mobile.webp",
      "alt": "Hero Mobile",
      "category": "Hero"
    }
  ],
  "pool": [
    {
      "jpg": "assets/images/pool/swimming-pool-01.jpg",
      "webp": "assets/images/pool/swimming-pool-01.webp",
      "alt": "Swimming Pool 01",
      "category": "Swimming Pool"
    },
    {
      "jpg": "assets/images/pool/swimming-pool-02.jpg",
      "webp": "assets/images/pool/swimming-pool-02.webp",
      "alt": "Swimming Pool 02",
      "category": "Swimming Pool"
    }
  ],
  "resort": [
    {
      "jpg": "assets/images/resort/SaveClip.App_724230430_17929143597337753_196008195900583165_n.jpg",
      "webp": "",
      "alt": "SaveClip.App 724230430 17929143597337753 196008195900583165 N",
      "category": "Resort"
    },
    {
      "jpg": "assets/images/resort/resort-exterior-01.jpg",
      "webp": "assets/images/resort/resort-exterior-01.webp",
      "alt": "Resort Exterior 01",
      "category": "Resort"
    },
    {
      "jpg": "assets/images/resort/resort-exterior-02.jpg",
      "webp": "assets/images/resort/resort-exterior-02.webp",
      "alt": "Resort Exterior 02",
      "category": "Resort"
    },
    {
      "jpg": "assets/images/resort/resort-riverfront-01.jpg",
      "webp": "assets/images/resort/resort-riverfront-01.webp",
      "alt": "Resort Riverfront 01",
      "category": "Resort"
    }
  ],
  "rooms": [
    {
      "jpg": "assets/images/rooms/room-01.jpg",
      "webp": "assets/images/rooms/room-01.webp",
      "alt": "Room 01",
      "category": "Rooms"
    },
    {
      "jpg": "assets/images/rooms/room-02.jpg",
      "webp": "assets/images/rooms/room-02.webp",
      "alt": "Room 02",
      "category": "Rooms"
    },
    {
      "jpg": "assets/images/rooms/room-03.jpg",
      "webp": "assets/images/rooms/room-03.webp",
      "alt": "Room 03",
      "category": "Rooms"
    },
    {
      "jpg": "assets/images/rooms/room-bathroom-01.jpg",
      "webp": "assets/images/rooms/room-bathroom-01.webp",
      "alt": "Room Bathroom 01",
      "category": "Rooms"
    }
  ],
  "surroundings": [
    {
      "jpg": "assets/images/surroundings/surroundings-01.jpg",
      "webp": "assets/images/surroundings/surroundings-01.webp",
      "alt": "Surroundings 01",
      "category": "Surroundings"
    },
    {
      "jpg": "assets/images/surroundings/surroundings-02.jpg",
      "webp": "assets/images/surroundings/surroundings-02.webp",
      "alt": "Surroundings 02",
      "category": "Surroundings"
    }
  ]
};
