/* AUTO-GENERATED by scripts/generate-images.py — do not edit by hand.
   Add photos to assets/images/<folder>/ and re-run the script. */
window.IMAGE_MANIFEST = {
  "version": 2,
  "order": [
    "gallery",
    "resort",
    "rooms",
    "pool",
    "food",
    "activities"
  ],
  "folders": {
    "activities": {
      "label": "Activities",
      "gallery": true,
      "images": [
        {
          "src": "assets/images/_optimized/activities/activity-group-02-1080.jpg",
          "original": "assets/images/activities/activity-group-02.jpg",
          "srcset": "assets/images/_optimized/activities/activity-group-02-480.webp 480w, assets/images/_optimized/activities/activity-group-02-960.webp 960w, assets/images/_optimized/activities/activity-group-02-1080.webp 1080w",
          "alt": "Activity Group 02",
          "w": 1080,
          "h": 1350
        },
        {
          "src": "assets/images/_optimized/activities/activity-group-03-1080.jpg",
          "original": "assets/images/activities/activity-group-03.jpg",
          "srcset": "assets/images/_optimized/activities/activity-group-03-480.webp 480w, assets/images/_optimized/activities/activity-group-03-960.webp 960w, assets/images/_optimized/activities/activity-group-03-1080.webp 1080w",
          "alt": "Activity Group 03",
          "w": 1080,
          "h": 1350
        },
        {
          "src": "assets/images/_optimized/activities/activity-group-04-1080.jpg",
          "original": "assets/images/activities/activity-group-04.jpg",
          "srcset": "assets/images/_optimized/activities/activity-group-04-480.webp 480w, assets/images/_optimized/activities/activity-group-04-960.webp 960w, assets/images/_optimized/activities/activity-group-04-1080.webp 1080w",
          "alt": "Activity Group 04",
          "w": 1080,
          "h": 1350
        },
        {
          "src": "assets/images/activities/activity-group-05.jpg",
          "original": "assets/images/activities/activity-group-05.jpg",
          "srcset": "assets/images/_optimized/activities/activity-group-05-480.webp 480w, assets/images/_optimized/activities/activity-group-05-960.webp 960w, assets/images/_optimized/activities/activity-group-05-1080.webp 1080w",
          "alt": "Activity Group 05",
          "w": 1080,
          "h": 1350
        },
        {
          "src": "assets/images/_optimized/activities/activity-group-06-1080.jpg",
          "original": "assets/images/activities/activity-group-06.jpg",
          "srcset": "assets/images/_optimized/activities/activity-group-06-480.webp 480w, assets/images/_optimized/activities/activity-group-06-960.webp 960w, assets/images/_optimized/activities/activity-group-06-1080.webp 1080w",
          "alt": "Activity Group 06",
          "w": 1080,
          "h": 1350
        },
        {
          "src": "assets/images/activities/activity-group-07.jpg",
          "original": "assets/images/activities/activity-group-07.jpg",
          "srcset": "assets/images/_optimized/activities/activity-group-07-480.webp 480w, assets/images/_optimized/activities/activity-group-07-960.webp 960w, assets/images/_optimized/activities/activity-group-07-1080.webp 1080w",
          "alt": "Activity Group 07",
          "w": 1080,
          "h": 1350
        }
      ]
    },
    "branding": {
      "label": "",
      "gallery": false,
      "images": [
        {
          "src": "assets/images/branding/resort-logo.png",
          "original": "assets/images/branding/resort-logo.png",
          "srcset": "assets/images/_optimized/branding/resort-logo-480.webp 480w, assets/images/_optimized/branding/resort-logo-960.webp 960w, assets/images/_optimized/branding/resort-logo-1080.webp 1080w",
          "alt": "Resort Logo",
          "w": 1080,
          "h": 1080
        }
      ]
    },
    "food": {
      "label": "Food",
      "gallery": true,
      "images": [
        {
          "src": "assets/images/food/SaveClip.App_630009485_17909303118337753_1059438545162966691_n.jpg",
          "original": "assets/images/food/SaveClip.App_630009485_17909303118337753_1059438545162966691_n.jpg",
          "srcset": "assets/images/_optimized/food/SaveClip.App_630009485_17909303118337753_1059438545162966691_n-480.webp 480w, assets/images/_optimized/food/SaveClip.App_630009485_17909303118337753_1059438545162966691_n-960.webp 960w, assets/images/_optimized/food/SaveClip.App_630009485_17909303118337753_1059438545162966691_n-1440.webp 1440w",
          "alt": "Food served at Bade Farms (1 of 6)",
          "w": 1440,
          "h": 1800
        },
        {
          "src": "assets/images/food/SaveClip.App_630108451_17909303145337753_8987344963266750178_n.jpg",
          "original": "assets/images/food/SaveClip.App_630108451_17909303145337753_8987344963266750178_n.jpg",
          "srcset": "assets/images/_optimized/food/SaveClip.App_630108451_17909303145337753_8987344963266750178_n-480.webp 480w, assets/images/_optimized/food/SaveClip.App_630108451_17909303145337753_8987344963266750178_n-960.webp 960w, assets/images/_optimized/food/SaveClip.App_630108451_17909303145337753_8987344963266750178_n-1440.webp 1440w",
          "alt": "Food served at Bade Farms (2 of 6)",
          "w": 1440,
          "h": 1800
        },
        {
          "src": "assets/images/food/SaveClip.App_630184206_17909303136337753_5257966624234150124_n.jpg",
          "original": "assets/images/food/SaveClip.App_630184206_17909303136337753_5257966624234150124_n.jpg",
          "srcset": "assets/images/_optimized/food/SaveClip.App_630184206_17909303136337753_5257966624234150124_n-480.webp 480w, assets/images/_optimized/food/SaveClip.App_630184206_17909303136337753_5257966624234150124_n-960.webp 960w, assets/images/_optimized/food/SaveClip.App_630184206_17909303136337753_5257966624234150124_n-1440.webp 1440w",
          "alt": "Food served at Bade Farms (3 of 6)",
          "w": 1440,
          "h": 1800
        },
        {
          "src": "assets/images/food/SaveClip.App_630206121_17909303127337753_4776752966663419988_n.jpg",
          "original": "assets/images/food/SaveClip.App_630206121_17909303127337753_4776752966663419988_n.jpg",
          "srcset": "assets/images/_optimized/food/SaveClip.App_630206121_17909303127337753_4776752966663419988_n-480.webp 480w, assets/images/_optimized/food/SaveClip.App_630206121_17909303127337753_4776752966663419988_n-960.webp 960w, assets/images/_optimized/food/SaveClip.App_630206121_17909303127337753_4776752966663419988_n-1440.webp 1440w",
          "alt": "Food served at Bade Farms (4 of 6)",
          "w": 1440,
          "h": 1800
        },
        {
          "src": "assets/images/food/SaveClip.App_696296505_969248349411165_3586370953481485829_n.jpg",
          "original": "assets/images/food/SaveClip.App_696296505_969248349411165_3586370953481485829_n.jpg",
          "srcset": "assets/images/_optimized/food/SaveClip.App_696296505_969248349411165_3586370953481485829_n-480.webp 480w, assets/images/_optimized/food/SaveClip.App_696296505_969248349411165_3586370953481485829_n-640.webp 640w",
          "alt": "Food served at Bade Farms (5 of 6)",
          "w": 640,
          "h": 800
        },
        {
          "src": "assets/images/food/SaveClip.App_707393633_17926417797337753_2143520799247043779_n.jpg",
          "original": "assets/images/food/SaveClip.App_707393633_17926417797337753_2143520799247043779_n.jpg",
          "srcset": "assets/images/_optimized/food/SaveClip.App_707393633_17926417797337753_2143520799247043779_n-480.webp 480w, assets/images/_optimized/food/SaveClip.App_707393633_17926417797337753_2143520799247043779_n-960.webp 960w, assets/images/_optimized/food/SaveClip.App_707393633_17926417797337753_2143520799247043779_n-1440.webp 1440w",
          "alt": "Food served at Bade Farms (6 of 6)",
          "w": 1440,
          "h": 1800
        }
      ]
    },
    "gallery": {
      "label": "Resort",
      "gallery": true,
      "images": [
        {
          "src": "assets/images/gallery/SaveClip.App_529855907_17887488453337753_5068259327826850295_n.jpg",
          "original": "assets/images/gallery/SaveClip.App_529855907_17887488453337753_5068259327826850295_n.jpg",
          "srcset": "assets/images/_optimized/gallery/SaveClip.App_529855907_17887488453337753_5068259327826850295_n-480.webp 480w, assets/images/_optimized/gallery/SaveClip.App_529855907_17887488453337753_5068259327826850295_n-960.webp 960w, assets/images/_optimized/gallery/SaveClip.App_529855907_17887488453337753_5068259327826850295_n-1440.webp 1440w",
          "alt": "The grounds at Bade Farms (1 of 7)",
          "w": 1440,
          "h": 1800
        },
        {
          "src": "assets/images/gallery/SaveClip.App_530543311_17887488498337753_9037298146911317242_n.jpg",
          "original": "assets/images/gallery/SaveClip.App_530543311_17887488498337753_9037298146911317242_n.jpg",
          "srcset": "assets/images/_optimized/gallery/SaveClip.App_530543311_17887488498337753_9037298146911317242_n-480.webp 480w, assets/images/_optimized/gallery/SaveClip.App_530543311_17887488498337753_9037298146911317242_n-960.webp 960w, assets/images/_optimized/gallery/SaveClip.App_530543311_17887488498337753_9037298146911317242_n-1440.webp 1440w",
          "alt": "The grounds at Bade Farms (2 of 7)",
          "w": 1440,
          "h": 1800
        },
        {
          "src": "assets/images/gallery/SaveClip.App_531211298_17887488489337753_3733645661466837347_n.jpg",
          "original": "assets/images/gallery/SaveClip.App_531211298_17887488489337753_3733645661466837347_n.jpg",
          "srcset": "assets/images/_optimized/gallery/SaveClip.App_531211298_17887488489337753_3733645661466837347_n-480.webp 480w, assets/images/_optimized/gallery/SaveClip.App_531211298_17887488489337753_3733645661466837347_n-960.webp 960w, assets/images/_optimized/gallery/SaveClip.App_531211298_17887488489337753_3733645661466837347_n-1440.webp 1440w",
          "alt": "The grounds at Bade Farms (3 of 7)",
          "w": 1440,
          "h": 1800
        },
        {
          "src": "assets/images/gallery/SaveClip.App_531408235_17887488444337753_197040834168579816_n.jpg",
          "original": "assets/images/gallery/SaveClip.App_531408235_17887488444337753_197040834168579816_n.jpg",
          "srcset": "assets/images/_optimized/gallery/SaveClip.App_531408235_17887488444337753_197040834168579816_n-480.webp 480w, assets/images/_optimized/gallery/SaveClip.App_531408235_17887488444337753_197040834168579816_n-960.webp 960w, assets/images/_optimized/gallery/SaveClip.App_531408235_17887488444337753_197040834168579816_n-1440.webp 1440w",
          "alt": "The grounds at Bade Farms (4 of 7)",
          "w": 1440,
          "h": 1800
        },
        {
          "src": "assets/images/gallery/SaveClip.App_532248537_17887488516337753_1380408753307852513_n.jpg",
          "original": "assets/images/gallery/SaveClip.App_532248537_17887488516337753_1380408753307852513_n.jpg",
          "srcset": "assets/images/_optimized/gallery/SaveClip.App_532248537_17887488516337753_1380408753307852513_n-480.webp 480w, assets/images/_optimized/gallery/SaveClip.App_532248537_17887488516337753_1380408753307852513_n-960.webp 960w, assets/images/_optimized/gallery/SaveClip.App_532248537_17887488516337753_1380408753307852513_n-1440.webp 1440w",
          "alt": "The grounds at Bade Farms (5 of 7)",
          "w": 1440,
          "h": 1800
        },
        {
          "src": "assets/images/_optimized/gallery/SaveClip.App_532660778_17887488462337753_8126991347647587568_n-1440.jpg",
          "original": "assets/images/gallery/SaveClip.App_532660778_17887488462337753_8126991347647587568_n.jpg",
          "srcset": "assets/images/_optimized/gallery/SaveClip.App_532660778_17887488462337753_8126991347647587568_n-480.webp 480w, assets/images/_optimized/gallery/SaveClip.App_532660778_17887488462337753_8126991347647587568_n-960.webp 960w, assets/images/_optimized/gallery/SaveClip.App_532660778_17887488462337753_8126991347647587568_n-1440.webp 1440w",
          "alt": "The grounds at Bade Farms (6 of 7)",
          "w": 1440,
          "h": 1800
        },
        {
          "src": "assets/images/_optimized/gallery/SaveClip.App_565462126_17895074739337753_2930093498321574042_n-1080.jpg",
          "original": "assets/images/gallery/SaveClip.App_565462126_17895074739337753_2930093498321574042_n.jpg",
          "srcset": "assets/images/_optimized/gallery/SaveClip.App_565462126_17895074739337753_2930093498321574042_n-480.webp 480w, assets/images/_optimized/gallery/SaveClip.App_565462126_17895074739337753_2930093498321574042_n-960.webp 960w, assets/images/_optimized/gallery/SaveClip.App_565462126_17895074739337753_2930093498321574042_n-1080.webp 1080w",
          "alt": "The grounds at Bade Farms (7 of 7)",
          "w": 1080,
          "h": 1350
        }
      ]
    },
    "hero": {
      "label": "",
      "gallery": false,
      "images": [
        {
          "src": "assets/images/hero/Bade.png",
          "original": "assets/images/hero/Bade.png",
          "srcset": "assets/images/_optimized/hero/Bade-480.webp 480w, assets/images/_optimized/hero/Bade-960.webp 960w, assets/images/_optimized/hero/Bade-1018.webp 1018w",
          "alt": "The villa and swimming pool at Bade Farms, Kolhapur",
          "w": 1018,
          "h": 449
        }
      ]
    },
    "pool": {
      "label": "Swimming Pool",
      "gallery": true,
      "images": [
        {
          "src": "assets/images/pool/SaveClip.App_532369698_17887488471337753_2515676446559289373_n.jpg",
          "original": "assets/images/pool/SaveClip.App_532369698_17887488471337753_2515676446559289373_n.jpg",
          "srcset": "assets/images/_optimized/pool/SaveClip.App_532369698_17887488471337753_2515676446559289373_n-480.webp 480w, assets/images/_optimized/pool/SaveClip.App_532369698_17887488471337753_2515676446559289373_n-960.webp 960w, assets/images/_optimized/pool/SaveClip.App_532369698_17887488471337753_2515676446559289373_n-1440.webp 1440w",
          "alt": "The swimming pool at Bade Farms (1 of 2)",
          "w": 1440,
          "h": 1800
        },
        {
          "src": "assets/images/_optimized/pool/SaveClip.App_563813874_17895074760337753_6719465863272514228_n-1080.jpg",
          "original": "assets/images/pool/SaveClip.App_563813874_17895074760337753_6719465863272514228_n.jpg",
          "srcset": "assets/images/_optimized/pool/SaveClip.App_563813874_17895074760337753_6719465863272514228_n-480.webp 480w, assets/images/_optimized/pool/SaveClip.App_563813874_17895074760337753_6719465863272514228_n-960.webp 960w, assets/images/_optimized/pool/SaveClip.App_563813874_17895074760337753_6719465863272514228_n-1080.webp 1080w",
          "alt": "The swimming pool at Bade Farms (2 of 2)",
          "w": 1080,
          "h": 1350
        }
      ]
    },
    "resort": {
      "label": "Resort",
      "gallery": true,
      "images": [
        {
          "src": "assets/images/_optimized/resort/SaveClip.App_724230430_17929143597337753_196008195900583165_n-1920.jpg",
          "original": "assets/images/resort/SaveClip.App_724230430_17929143597337753_196008195900583165_n.jpg",
          "srcset": "assets/images/_optimized/resort/SaveClip.App_724230430_17929143597337753_196008195900583165_n-480.webp 480w, assets/images/_optimized/resort/SaveClip.App_724230430_17929143597337753_196008195900583165_n-960.webp 960w, assets/images/_optimized/resort/SaveClip.App_724230430_17929143597337753_196008195900583165_n-1440.webp 1440w, assets/images/_optimized/resort/SaveClip.App_724230430_17929143597337753_196008195900583165_n-1920.webp 1920w, assets/images/_optimized/resort/SaveClip.App_724230430_17929143597337753_196008195900583165_n-2025.webp 2025w",
          "alt": "The villa at Bade Farms",
          "w": 2025,
          "h": 2531
        }
      ]
    },
    "rooms": {
      "label": "Rooms",
      "gallery": true,
      "images": [
        {
          "src": "assets/images/rooms/SaveClip.App_530924145_17887488507337753_2216503104786821007_n.jpg",
          "original": "assets/images/rooms/SaveClip.App_530924145_17887488507337753_2216503104786821007_n.jpg",
          "srcset": "assets/images/_optimized/rooms/SaveClip.App_530924145_17887488507337753_2216503104786821007_n-480.webp 480w, assets/images/_optimized/rooms/SaveClip.App_530924145_17887488507337753_2216503104786821007_n-960.webp 960w, assets/images/_optimized/rooms/SaveClip.App_530924145_17887488507337753_2216503104786821007_n-1440.webp 1440w",
          "alt": "A bedroom at Bade Farms (1 of 2)",
          "w": 1440,
          "h": 1800
        },
        {
          "src": "assets/images/rooms/SaveClip.App_565412821_17895074748337753_8244442311990717578_n.jpg",
          "original": "assets/images/rooms/SaveClip.App_565412821_17895074748337753_8244442311990717578_n.jpg",
          "srcset": "assets/images/_optimized/rooms/SaveClip.App_565412821_17895074748337753_8244442311990717578_n-480.webp 480w, assets/images/_optimized/rooms/SaveClip.App_565412821_17895074748337753_8244442311990717578_n-960.webp 960w, assets/images/_optimized/rooms/SaveClip.App_565412821_17895074748337753_8244442311990717578_n-1080.webp 1080w",
          "alt": "A bedroom at Bade Farms (2 of 2)",
          "w": 1080,
          "h": 1350
        }
      ]
    },
    "surroundings": {
      "label": "Surroundings",
      "gallery": false,
      "images": [
        {
          "src": "assets/images/surroundings/surroundings-01.jpg",
          "original": "assets/images/surroundings/surroundings-01.jpg",
          "srcset": "assets/images/_optimized/surroundings/surroundings-01-480.webp 480w, assets/images/_optimized/surroundings/surroundings-01-960.webp 960w, assets/images/_optimized/surroundings/surroundings-01-1440.webp 1440w, assets/images/_optimized/surroundings/surroundings-01-1600.webp 1600w",
          "alt": "Surroundings 01",
          "w": 1600,
          "h": 900
        },
        {
          "src": "assets/images/surroundings/surroundings-02.jpg",
          "original": "assets/images/surroundings/surroundings-02.jpg",
          "srcset": "assets/images/_optimized/surroundings/surroundings-02-480.webp 480w, assets/images/_optimized/surroundings/surroundings-02-960.webp 960w, assets/images/_optimized/surroundings/surroundings-02-1440.webp 1440w, assets/images/_optimized/surroundings/surroundings-02-1600.webp 1600w",
          "alt": "Surroundings 02",
          "w": 1600,
          "h": 900
        }
      ]
    }
  }
};
