/* AUTO-GENERATED by scripts/generate-images.py — do not edit. */
window.IMAGE_MANIFEST = {
  "activities": [
    {
      "jpg": "assets/images/activities/activity-group-02.jpg",
      "webp": "",
      "alt": "Activity Group 02",
      "category": "Activities"
    },
    {
      "jpg": "assets/images/activities/activity-group-03.jpg",
      "webp": "",
      "alt": "Activity Group 03",
      "category": "Activities"
    },
    {
      "jpg": "assets/images/activities/activity-group-04.jpg",
      "webp": "",
      "alt": "Activity Group 04",
      "category": "Activities"
    },
    {
      "jpg": "assets/images/activities/activity-group-05.jpg",
      "webp": "",
      "alt": "Activity Group 05",
      "category": "Activities"
    },
    {
      "jpg": "assets/images/activities/activity-group-06.jpg",
      "webp": "",
      "alt": "Activity Group 06",
      "category": "Activities"
    },
    {
      "jpg": "assets/images/activities/activity-group-07.jpg",
      "webp": "",
      "alt": "Activity Group 07",
      "category": "Activities"
    }
  ],
  "branding": [
    {
      "jpg": "assets/images/branding/resort-logo.png",
      "webp": "",
      "alt": "Resort Logo",
      "category": ""
    }
  ],
  "food": [
    {
      "jpg": "assets/images/food/SaveClip.App_630009485_17909303118337753_1059438545162966691_n.jpg",
      "webp": "",
      "alt": "SaveClip.App 630009485 17909303118337753 1059438545162966691 N",
      "category": "Food"
    },
    {
      "jpg": "assets/images/food/SaveClip.App_630108451_17909303145337753_8987344963266750178_n.jpg",
      "webp": "",
      "alt": "SaveClip.App 630108451 17909303145337753 8987344963266750178 N",
      "category": "Food"
    },
    {
      "jpg": "assets/images/food/SaveClip.App_630184206_17909303136337753_5257966624234150124_n.jpg",
      "webp": "",
      "alt": "SaveClip.App 630184206 17909303136337753 5257966624234150124 N",
      "category": "Food"
    },
    {
      "jpg": "assets/images/food/SaveClip.App_630206121_17909303127337753_4776752966663419988_n.jpg",
      "webp": "",
      "alt": "SaveClip.App 630206121 17909303127337753 4776752966663419988 N",
      "category": "Food"
    },
    {
      "jpg": "assets/images/food/SaveClip.App_696296505_969248349411165_3586370953481485829_n.jpg",
      "webp": "",
      "alt": "SaveClip.App 696296505 969248349411165 3586370953481485829 N",
      "category": "Food"
    },
    {
      "jpg": "assets/images/food/SaveClip.App_707393633_17926417797337753_2143520799247043779_n.jpg",
      "webp": "",
      "alt": "SaveClip.App 707393633 17926417797337753 2143520799247043779 N",
      "category": "Food"
    }
  ],
  "gallery": [
    {
      "jpg": "assets/images/gallery/SaveClip.App_529855907_17887488453337753_5068259327826850295_n.jpg",
      "webp": "",
      "alt": "SaveClip.App 529855907 17887488453337753 5068259327826850295 N",
      "category": "Resort"
    },
    {
      "jpg": "assets/images/gallery/SaveClip.App_530543311_17887488498337753_9037298146911317242_n.jpg",
      "webp": "",
      "alt": "SaveClip.App 530543311 17887488498337753 9037298146911317242 N",
      "category": "Resort"
    },
    {
      "jpg": "assets/images/gallery/SaveClip.App_531211298_17887488489337753_3733645661466837347_n.jpg",
      "webp": "",
      "alt": "SaveClip.App 531211298 17887488489337753 3733645661466837347 N",
      "category": "Resort"
    },
    {
      "jpg": "assets/images/gallery/SaveClip.App_531408235_17887488444337753_197040834168579816_n.jpg",
      "webp": "",
      "alt": "SaveClip.App 531408235 17887488444337753 197040834168579816 N",
      "category": "Resort"
    },
    {
      "jpg": "assets/images/gallery/SaveClip.App_532248537_17887488516337753_1380408753307852513_n.jpg",
      "webp": "",
      "alt": "SaveClip.App 532248537 17887488516337753 1380408753307852513 N",
      "category": "Resort"
    },
    {
      "jpg": "assets/images/gallery/SaveClip.App_532660778_17887488462337753_8126991347647587568_n.jpg",
      "webp": "",
      "alt": "SaveClip.App 532660778 17887488462337753 8126991347647587568 N",
      "category": "Resort"
    },
    {
      "jpg": "assets/images/gallery/SaveClip.App_565462126_17895074739337753_2930093498321574042_n.jpg",
      "webp": "",
      "alt": "SaveClip.App 565462126 17895074739337753 2930093498321574042 N",
      "category": "Resort"
    }
  ],
  "hero": [
    {
      "jpg": "assets/images/hero/Gemini_Generated_Image_fxf8qvfxf8qvfxf8.png",
      "webp": "",
      "alt": "Gemini Generated Image Fxf8qvfxf8qvfxf8",
      "category": "Hero"
    },
    {
      "jpg": "assets/images/hero/Gemini_Generated_Image_yl0414yl0414yl04.png",
      "webp": "",
      "alt": "Gemini Generated Image Yl0414yl0414yl04",
      "category": "Hero"
    }
  ],
  "pool": [
    {
      "jpg": "assets/images/pool/SaveClip.App_532369698_17887488471337753_2515676446559289373_n.jpg",
      "webp": "",
      "alt": "SaveClip.App 532369698 17887488471337753 2515676446559289373 N",
      "category": "Swimming Pool"
    },
    {
      "jpg": "assets/images/pool/SaveClip.App_563813874_17895074760337753_6719465863272514228_n.jpg",
      "webp": "",
      "alt": "SaveClip.App 563813874 17895074760337753 6719465863272514228 N",
      "category": "Swimming Pool"
    }
  ],
  "resort": [
    {
      "jpg": "assets/images/resort/SaveClip.App_724230430_17929143597337753_196008195900583165_n.jpg",
      "webp": "",
      "alt": "SaveClip.App 724230430 17929143597337753 196008195900583165 N",
      "category": "Resort"
    }
  ],
  "rooms": [
    {
      "jpg": "assets/images/rooms/SaveClip.App_530924145_17887488507337753_2216503104786821007_n.jpg",
      "webp": "",
      "alt": "SaveClip.App 530924145 17887488507337753 2216503104786821007 N",
      "category": "Rooms"
    },
    {
      "jpg": "assets/images/rooms/SaveClip.App_565412821_17895074748337753_8244442311990717578_n.jpg",
      "webp": "",
      "alt": "SaveClip.App 565412821 17895074748337753 8244442311990717578 N",
      "category": "Rooms"
    }
  ],
  "surroundings": [
    {
      "jpg": "assets/images/surroundings/surroundings-01.jpg",
      "webp": "assets/images/surroundings/surroundings-01.webp",
      "alt": "Surroundings 01",
      "category": "Surroundings"
    },
    {
      "jpg": "assets/images/surroundings/surroundings-02.jpg",
      "webp": "assets/images/surroundings/surroundings-02.webp",
      "alt": "Surroundings 02",
      "category": "Surroundings"
    }
  ]
};
