#!/usr/bin/env python3
"""
Download the web fonts into assets/fonts/ and write css/fonts.css.

The site self-hosts its fonts so that:
  * no request goes to Google before a visitor has interacted with the page
    (relevant for privacy notices and consent rules), and
  * text paints without a third-party DNS + TLS round trip.

Only the latin and latin-ext subsets are kept. Browsers fetch just the files
they actually need, thanks to the unicode-range and weight declarations.

Run this only if you change the fonts:
    python scripts/fetch-fonts.py
"""

import os
import re
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_DIR = os.path.join(ROOT, "assets", "fonts")
OUT_CSS = os.path.join(ROOT, "css", "fonts.css")

# Google's CSS API serves modern woff2 only when it thinks the client is a
# modern browser, so send a browser user agent.
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")

API = (
    "https://fonts.googleapis.com/css2?"
    "family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;0,600;1,300;1,400"
    "&family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap"
)

KEEP_SUBSETS = ("latin", "latin-ext")


def fetch(url, binary=False):
    request = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(request, timeout=40) as response:
        return response.read() if binary else response.read().decode("utf-8")


def main():
    os.makedirs(FONT_DIR, exist_ok=True)
    css = fetch(API)

    blocks = re.findall(r"(/\*\s*([\w-]+)\s*\*/\s*@font-face\s*\{[^}]*\})", css)
    if not blocks:
        raise SystemExit("Could not parse the Google Fonts response.")

    kept, sizes = [], {}
    for block, subset in blocks:
        if subset not in KEEP_SUBSETS:
            continue
        url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
        family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        weight = re.search(r"font-weight:\s*(\d+)", block).group(1)
        style = re.search(r"font-style:\s*(\w+)", block).group(1)

        slug = family.lower().replace(" ", "-")
        italic = "-italic" if style == "italic" else ""
        name = "%s-%s%s-%s.woff2" % (slug, weight, italic, subset)
        path = os.path.join(FONT_DIR, name)

        if not os.path.exists(path):
            with open(path, "wb") as fh:
                fh.write(fetch(url, binary=True))
        # css/fonts.css lives in css/, so step up one level.
        kept.append(block.replace(url, "../assets/fonts/" + name))
        sizes[name] = os.path.getsize(path)

    header = (
        "/* AUTO-GENERATED by scripts/fetch-fonts.py — do not edit by hand.\n"
        "   Self-hosted Google Fonts, latin + latin-ext subsets only. */\n\n"
    )
    with open(OUT_CSS, "w", encoding="utf-8", newline="") as fh:
        fh.write(header + "\n\n".join(b.strip() for b in kept) + "\n")

    print("Wrote css/fonts.css and %d font file(s), %.0f KB total"
          % (len(sizes), sum(sizes.values()) / 1024))


if __name__ == "__main__":
    main()
