#!/usr/bin/env python3
"""
Scan every photo inside assets/images/<category>/ and write js/images.js.

This removes the need for naming conventions: drop ANY .jpg/.jpeg/.png into a
folder, run this script, refresh the page. The website picks up the images
automatically.

Usage (from the project folder):
    python scripts/generate-images.py
"""

import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IMAGES_DIR = os.path.join(ROOT, "assets", "images")
OUT_FILE = os.path.join(ROOT, "js", "images.js")

IMAGE_EXTS = re.compile(r"\.(jpg|jpeg|png|gif)$", re.IGNORECASE)

# folder name -> gallery filter category shown on the site
CATEGORY_LABELS = {
    "branding": "",
    "hero": "Hero",
    "resort": "Resort",
    "rooms": "Rooms",
    "camping": "Camping",
    "pool": "Swimming Pool",
    "food": "Food",
    "activities": "Activities",
    "surroundings": "Surroundings",
    "gallery": "Resort",
}


def humanize(filename):
    """Turn 'activity-family-01.jpg' into 'Activity Family 01' for alt text."""
    base = IMAGE_EXTS.sub("", filename)
    base = re.sub(r"[-_]+", " ", base).strip()
    words = [w[:1].upper() + w[1:] for w in base.split() if w]
    return " ".join(words) if words else "Photo"


def scan_folder(folder):
    folder_path = os.path.join(IMAGES_DIR, folder)
    if not os.path.isdir(folder_path):
        return []
    images = []
    files = sorted(
        f for f in os.listdir(folder_path) if IMAGE_EXTS.search(f)
    )
    for f in files:
        rel = "assets/images/%s/%s" % (folder, f)
        # Only point at a .webp when that file actually exists next to it.
        webp_name = IMAGE_EXTS.sub(".webp", f)
        webp = ""
        if webp_name != f and os.path.isfile(os.path.join(folder_path, webp_name)):
            webp = "assets/images/%s/%s" % (folder, webp_name)
        images.append({
            "jpg": rel,
            "webp": webp,
            "alt": humanize(f),
            "category": CATEGORY_LABELS.get(folder, humanize(folder)),
        })
    return images


def main():
    manifest = {}
    if not os.path.isdir(IMAGES_DIR):
        raise SystemExit("Folder not found: %s" % IMAGES_DIR)
    for folder in sorted(os.listdir(IMAGES_DIR)):
        folder_path = os.path.join(IMAGES_DIR, folder)
        if os.path.isdir(folder_path):
            images = scan_folder(folder)
            if images:
                manifest[folder] = images

    with open(OUT_FILE, "w", encoding="utf-8") as fh:
        fh.write(
            "/* AUTO-GENERATED by scripts/generate-images.py — do not edit. */\n"
        )
        fh.write("window.IMAGE_MANIFEST = ")
        fh.write(json.dumps(manifest, ensure_ascii=False, indent=2))
        fh.write(";\n")

    total = sum(len(v) for v in manifest.values())
    print("Wrote %s (%d images across %d folders)" % (OUT_FILE, total, len(manifest)))
    for folder, images in manifest.items():
        print("  %-14s %d image(s)" % (folder, len(images)))


if __name__ == "__main__":
    main()